//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LAListener.h"

@class NSString;

@interface ZMActivatorListener : NSObject <LAListener>
{
}

+ (void)load;
- (id)activator:(id)arg1 requiresSmallIconForListenerName:(id)arg2 scale:(double)arg3;
- (id)activator:(id)arg1 requiresIconForListenerName:(id)arg2 scale:(double)arg3;
- (id)activator:(id)arg1 requiresLocalizedDescriptionForListenerName:(id)arg2;
- (id)activator:(id)arg1 requiresLocalizedTitleForListenerName:(id)arg2;
- (void)activator:(id)arg1 receiveEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

