//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIToolbar, ZMRecentAppsView, ZMSettings;

@interface ZMClearAllAppsView : UIView
{
    ZMSettings *_settings;
    UIToolbar *_blurView;
    UIButton *_clearAllNotificationsButton;
    _Bool _isActive;
    ZMRecentAppsView *_delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak ZMRecentAppsView *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
- (void).cxx_destruct;
- (void)clearAllNotificationsButtonReleased:(id)arg1;
- (void)singleFingerTapRecognizer:(id)arg1;
- (void)panGestureRecognizer:(id)arg1;
- (void)hide;
- (void)show;
- (void)changeFrame:(struct CGRect)arg1;
- (id)init;

@end

