//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, UIImageView, UISlider, ZMSettings, ZMView;

@interface ZMControlTogglesView : UIView
{
    _Bool _enabled;
    ZMSettings *_settings;
    UIImageView *_airplaneButtonImageView;
    UIImage *_airplaneButtonEnabledImage;
    UIImage *_airplaneButtonDisabledImage;
    UIImageView *_wifiButtonImageView;
    UIImage *_wifiButtonEnabledImage;
    UIImage *_wifiButtonDisabledImage;
    UIImageView *_bluetoothButtonImageView;
    UIImage *_bluetoothButtonEnabledImage;
    UIImage *_bluetoothButtonDisabledImage;
    UIImageView *_doNotDisturbButtonImageView;
    UIImage *_doNotDisturbButtonEnabledImage;
    UIImage *_doNotDisturbButtonDisabledImage;
    UIImageView *_rotateButtonImageView;
    UIImage *_rotateButtonEnabledImage;
    UIImage *_rotateButtonDisabledImage;
    UIView *_brightnessSliderBlackOverlayView;
    UISlider *_brightnessSlider;
    UIImageView *_brightnessMinImageView;
    UIImageView *_brightnessMaxImageView;
    UIImageView *_flashlightButtonImageView;
    UIImage *_flashlightButtonEnabledImage;
    UIImage *_flashlightButtonDisabledImage;
    UIImageView *_clockButtonImageView;
    UIImage *_clockButtonEnabledImage;
    UIImage *_clockButtonDisabledImage;
    UIImageView *_calculatorButtonImageView;
    UIImage *_calculatorButtonEnabledImage;
    UIImage *_calculatorButtonDisabledImage;
    UIImageView *_cameraButtonImageView;
    UIImage *_cameraButtonEnabledImage;
    UIImage *_cameraButtonDisabledImage;
    ZMView *_delegate;
}

@property(nonatomic) __weak ZMView *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cameraButtonSingleTapRecognizer:(id)arg1;
- (void)calculatorButtonSingleTapRecognizer:(id)arg1;
- (void)clockButtonSingleTapRecognizer:(id)arg1;
- (void)flashlightButtonSingleTapRecognizer:(id)arg1;
- (void)brightnessSliderValueChanged:(id)arg1;
- (void)rotateButtonSingleTapRecognizer:(id)arg1;
- (void)doNotDisturbButtonSingleTapRecognizer:(id)arg1;
- (void)bluetoothButtonSingleTapRecognizer:(id)arg1;
- (void)wifiButtonSingleTapRecognizer:(id)arg1;
- (void)airplaneButtonSingleTapRecognizer:(id)arg1;
- (void)updateTimer:(id)arg1;
- (void)updateFrame;
- (double)height;
- (double)width;
- (id)initWithDelegate:(id)arg1;

@end

