//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class TWAppItem, UILabel, ZMAppPanelView;

@interface ZMIconImageView : UIImageView
{
    ZMAppPanelView *_delegate;
    TWAppItem *_appItem;
    UILabel *_appNameLabel;
}

@property(retain, nonatomic) UILabel *appNameLabel; // @synthesize appNameLabel=_appNameLabel;
@property(retain, nonatomic) TWAppItem *appItem; // @synthesize appItem=_appItem;
@property(nonatomic) __weak ZMAppPanelView *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)singleFingerTapRecognizer:(id)arg1;
- (id)initWithAppItem:(id)arg1;

@end

