//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, SBMediaController, TWMusicProvider, UIImage, UIImageView, UILabel, UISlider, ZMSettings, ZMView;

@interface ZMMusicPlayerView : UIView
{
    _Bool _enabled;
    ZMSettings *_settings;
    TWMusicProvider *_musicProvider;
    SBMediaController *_mediaController;
    NSString *_nowPlayingAppBundleIdentifer;
    NSString *_fallbackBundleIdentifer;
    UIImageView *_nowPlayingArtworkImageView;
    UILabel *_songNameLabel;
    UILabel *_artistAndAlbumNameLabel;
    UIImageView *_playPauseButtonImageView;
    UIImage *_playButtonImage;
    UIImage *_pauseButtonImage;
    UIImageView *_prevButtonImageView;
    UIImageView *_nextButtonImageView;
    UIImageView *_shuffleButtonImageView;
    UIImageView *_repeatButtonImageView;
    UISlider *_volumeSlider;
    UIImageView *_volumeMinImageView;
    UIImageView *_volumeMaxImageView;
    ZMView *_delegate;
}

@property(nonatomic) __weak ZMView *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)volumeSliderValueChanged:(id)arg1;
- (void)repeatButtonSingleTapRecognizer:(id)arg1;
- (void)shuffleButtonSingleTapRecognizer:(id)arg1;
- (void)prevButtonSingleTapRecognizer:(id)arg1;
- (void)nextButtonSingleTapRecognizer:(id)arg1;
- (void)playPauseButtonSingleTapRecognizer:(id)arg1;
- (void)artworkSingleTapRecognizer:(id)arg1;
- (void)update;
- (void)updateTimer:(id)arg1;
- (void)updateFrame;
- (double)height;
- (double)width;
- (id)initWithDelegate:(id)arg1;

@end

