//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary, UIImageView, UIScrollView, ZMSettings, ZMView;

@interface ZMRecentAppsView : UIView
{
    ZMSettings *_settings;
    UIScrollView *_scrollView;
    UIView *_homeScreenCardView;
    UIImageView *_homeScreenCardIconImageView;
    _Bool _showHomeScreenCard;
    double _snapshotWidth;
    double _snapshotHeight;
    double _padding;
    double _spacing;
    ZMView *_delegate;
    NSMutableDictionary *_snapshotViewsCache;
    NSMutableArray *_snapshotViews;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) NSMutableArray *snapshotViews; // @synthesize snapshotViews=_snapshotViews;
@property(retain, nonatomic) NSMutableDictionary *snapshotViewsCache; // @synthesize snapshotViewsCache=_snapshotViewsCache;
@property(nonatomic) __weak ZMView *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)homeScreenCardLongPressRecognizer:(id)arg1;
- (void)homeScreenCardSingleFingerTapRecognizer:(id)arg1;
- (void)updateAppPositions;
- (void)updateApps;
- (void)updateFrame;
- (id)initWithDelegate:(id)arg1;

@end

