//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TWAppItem, UILabel, ZMRecentAppsView, ZMSettings;

@interface ZMSnapshotView : UIView
{
    ZMSettings *_settings;
    ZMRecentAppsView *_delegate;
    TWAppItem *_appItem;
    UILabel *_appNameLabel;
}

@property(retain, nonatomic) UILabel *appNameLabel; // @synthesize appNameLabel=_appNameLabel;
@property(retain, nonatomic) TWAppItem *appItem; // @synthesize appItem=_appItem;
@property(nonatomic) __weak ZMRecentAppsView *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)randomRemove;
- (void)performRemovalAndUpdateAppPositions;
- (void)performRemoval;
- (void)swipeUpGestureRecognizer:(id)arg1;
- (void)swipeDownGestureRecognizer:(id)arg1;
- (void)singleFingerTapRecognizer:(id)arg1;
- (id)initWithAppItem:(id)arg1;

@end

