//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TWContainerWindowViewDelegate.h"

@class NSMutableDictionary, NSString, TWContainerWindow, UIImageView, UIScrollView, UIVisualEffectView, ZMAppPanelView, ZMControlTogglesView, ZMMusicPlayerView, ZMRecentAppsView, ZMScrollView, ZMSettings;

@interface ZMView : UIView <TWContainerWindowViewDelegate>
{
    TWContainerWindow *_containerWindow;
    ZMSettings *_settings;
    UIImageView *_wallpaperImageView;
    UIVisualEffectView *_blurEffectView;
    UIView *_topContainerView;
    UIView *_topBlackOverlayView;
    UIView *_bottomContainerView;
    UIView *_blackOverlayView;
    ZMAppPanelView *_appPanelView;
    ZMScrollView *_scrollView;
    ZMControlTogglesView *_controlTogglesView;
    ZMMusicPlayerView *_musicPlayerView;
    ZMRecentAppsView *_recentAppsView;
    NSMutableDictionary *_pageCache;
    NSString *_previousPage;
    _Bool _isPortrait;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool isPortrait; // @synthesize isPortrait=_isPortrait;
- (void).cxx_destruct;
@property(readonly, retain, nonatomic) UIScrollView *scrollView;
@property(readonly, retain, nonatomic) UIView *bottomContainerView;
@property(readonly, retain, nonatomic) UIView *topContainerView;
- (void)updateFrame;
- (void)viewWillHide;
- (void)viewWillShow;
@property(readonly, nonatomic) double height;
@property(readonly, nonatomic) double width;
- (id)init;
@property(readonly, nonatomic) _Bool isActive;
- (void)hide;
- (void)show;

@end

